/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser";

export type * from "../models";
export type * from "./prismaNamespace";

export const Decimal = runtime.Decimal;

export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as new (
    secret: never,
  ) => typeof runtime.objectEnumValues.instances.DbNull,
  JsonNull: runtime.objectEnumValues.classes.JsonNull as new (
    secret: never,
  ) => typeof runtime.objectEnumValues.instances.JsonNull,
  AnyNull: runtime.objectEnumValues.classes.AnyNull as new (
    secret: never,
  ) => typeof runtime.objectEnumValues.instances.AnyNull,
};
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull;
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull;
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull;

export const ModelName = {
  Account: "Account",
  Session: "Session",
  User: "User",
  VerificationToken: "VerificationToken",
  Restaurant: "Restaurant",
  UserFavoriteRestaurant: "UserFavoriteRestaurant",
  Category: "Category",
  ProductAccompaniment: "ProductAccompaniment",
  Product: "Product",
  OrderProduct: "OrderProduct",
  Order: "Order",
} as const;

export type ModelName = (typeof ModelName)[keyof typeof ModelName];

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable",
} as const);

export type TransactionIsolationLevel =
  (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel];

export const AccountScalarFieldEnum = {
  id: "id",
  userId: "userId",
  type: "type",
  provider: "provider",
  providerAccountId: "providerAccountId",
  refresh_token: "refresh_token",
  access_token: "access_token",
  expires_at: "expires_at",
  token_type: "token_type",
  scope: "scope",
  id_token: "id_token",
  session_state: "session_state",
} as const;

export type AccountScalarFieldEnum =
  (typeof AccountScalarFieldEnum)[keyof typeof AccountScalarFieldEnum];

export const SessionScalarFieldEnum = {
  id: "id",
  sessionToken: "sessionToken",
  userId: "userId",
  expires: "expires",
} as const;

export type SessionScalarFieldEnum =
  (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum];

export const UserScalarFieldEnum = {
  id: "id",
  name: "name",
  email: "email",
  emailVerified: "emailVerified",
  image: "image",
  password: "password",
} as const;

export type UserScalarFieldEnum =
  (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum];

export const VerificationTokenScalarFieldEnum = {
  identifier: "identifier",
  token: "token",
  expires: "expires",
} as const;

export type VerificationTokenScalarFieldEnum =
  (typeof VerificationTokenScalarFieldEnum)[keyof typeof VerificationTokenScalarFieldEnum];

export const RestaurantScalarFieldEnum = {
  id: "id",
  name: "name",
  imageUrl: "imageUrl",
  deliveryFee: "deliveryFee",
  deliveryTimeMinutes: "deliveryTimeMinutes",
} as const;

export type RestaurantScalarFieldEnum =
  (typeof RestaurantScalarFieldEnum)[keyof typeof RestaurantScalarFieldEnum];

export const UserFavoriteRestaurantScalarFieldEnum = {
  userId: "userId",
  restaurantId: "restaurantId",
  createdAt: "createdAt",
} as const;

export type UserFavoriteRestaurantScalarFieldEnum =
  (typeof UserFavoriteRestaurantScalarFieldEnum)[keyof typeof UserFavoriteRestaurantScalarFieldEnum];

export const CategoryScalarFieldEnum = {
  id: "id",
  name: "name",
  imageUrl: "imageUrl",
  createdAt: "createdAt",
} as const;

export type CategoryScalarFieldEnum =
  (typeof CategoryScalarFieldEnum)[keyof typeof CategoryScalarFieldEnum];

export const ProductAccompanimentScalarFieldEnum = {
  id: "id",
  label: "label",
  productId: "productId",
} as const;

export type ProductAccompanimentScalarFieldEnum =
  (typeof ProductAccompanimentScalarFieldEnum)[keyof typeof ProductAccompanimentScalarFieldEnum];

export const ProductScalarFieldEnum = {
  id: "id",
  name: "name",
  description: "description",
  imageUrl: "imageUrl",
  price: "price",
  discountPercentage: "discountPercentage",
  restaurantId: "restaurantId",
  categoryId: "categoryId",
  createdAt: "createdAt",
} as const;

export type ProductScalarFieldEnum =
  (typeof ProductScalarFieldEnum)[keyof typeof ProductScalarFieldEnum];

export const OrderProductScalarFieldEnum = {
  id: "id",
  orderId: "orderId",
  productId: "productId",
  quantity: "quantity",
} as const;

export type OrderProductScalarFieldEnum =
  (typeof OrderProductScalarFieldEnum)[keyof typeof OrderProductScalarFieldEnum];

export const OrderScalarFieldEnum = {
  id: "id",
  userId: "userId",
  restaurantId: "restaurantId",
  deliveryFee: "deliveryFee",
  deliveryTimeMinutes: "deliveryTimeMinutes",
  subtotalPrice: "subtotalPrice",
  totalPrice: "totalPrice",
  totalDiscounts: "totalDiscounts",
  street: "street",
  number: "number",
  neighborhood: "neighborhood",
  city: "city",
  state: "state",
  createdAt: "createdAt",
  status: "status",
} as const;

export type OrderScalarFieldEnum =
  (typeof OrderScalarFieldEnum)[keyof typeof OrderScalarFieldEnum];

export const SortOrder = {
  asc: "asc",
  desc: "desc",
} as const;

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder];

export const QueryMode = {
  default: "default",
  insensitive: "insensitive",
} as const;

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode];

export const NullsOrder = {
  first: "first",
  last: "last",
} as const;

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder];
