/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck
/*
 * This file exports all enum related types from the schema.
 *
 * 🟢 You can import this file directly.
 */

export const OrderStatus = {
  CONFIRMED: "CONFIRMED",
  CANCELED: "CANCELED",
  PREPARING: "PREPARING",
  DELIVERING: "DELIVERING",
  COMPLETED: "COMPLETED",
} as const;

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus];
