/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from "./models/Account";
export type * from "./models/Session";
export type * from "./models/User";
export type * from "./models/VerificationToken";
export type * from "./models/Restaurant";
export type * from "./models/UserFavoriteRestaurant";
export type * from "./models/Category";
export type * from "./models/ProductAccompaniment";
export type * from "./models/Product";
export type * from "./models/OrderProduct";
export type * from "./models/Order";
export type * from "./commonInputTypes";
