/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck
/*
 * This file exports the `ProductAccompaniment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library";
import type * as $Enums from "../enums";
import type * as Prisma from "../internal/prismaNamespace";

/**
 * Model ProductAccompaniment
 *
 */
export type ProductAccompanimentModel =
  runtime.Types.Result.DefaultSelection<Prisma.$ProductAccompanimentPayload>;

export type AggregateProductAccompaniment = {
  _count: ProductAccompanimentCountAggregateOutputType | null;
  _min: ProductAccompanimentMinAggregateOutputType | null;
  _max: ProductAccompanimentMaxAggregateOutputType | null;
};

export type ProductAccompanimentMinAggregateOutputType = {
  id: string | null;
  label: string | null;
  productId: string | null;
};

export type ProductAccompanimentMaxAggregateOutputType = {
  id: string | null;
  label: string | null;
  productId: string | null;
};

export type ProductAccompanimentCountAggregateOutputType = {
  id: number;
  label: number;
  productId: number;
  _all: number;
};

export type ProductAccompanimentMinAggregateInputType = {
  id?: true;
  label?: true;
  productId?: true;
};

export type ProductAccompanimentMaxAggregateInputType = {
  id?: true;
  label?: true;
  productId?: true;
};

export type ProductAccompanimentCountAggregateInputType = {
  id?: true;
  label?: true;
  productId?: true;
  _all?: true;
};

export type ProductAccompanimentAggregateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which ProductAccompaniment to aggregate.
   */
  where?: Prisma.ProductAccompanimentWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ProductAccompaniments to fetch.
   */
  orderBy?:
    | Prisma.ProductAccompanimentOrderByWithRelationInput
    | Prisma.ProductAccompanimentOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.ProductAccompanimentWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ProductAccompaniments from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ProductAccompaniments.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned ProductAccompaniments
   **/
  _count?: true | ProductAccompanimentCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: ProductAccompanimentMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: ProductAccompanimentMaxAggregateInputType;
};

export type GetProductAccompanimentAggregateType<
  T extends ProductAccompanimentAggregateArgs,
> = {
  [P in keyof T & keyof AggregateProductAccompaniment]: P extends
    | "_count"
    | "count"
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProductAccompaniment[P]>
    : Prisma.GetScalarType<T[P], AggregateProductAccompaniment[P]>;
};

export type ProductAccompanimentGroupByArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.ProductAccompanimentWhereInput;
  orderBy?:
    | Prisma.ProductAccompanimentOrderByWithAggregationInput
    | Prisma.ProductAccompanimentOrderByWithAggregationInput[];
  by:
    | Prisma.ProductAccompanimentScalarFieldEnum[]
    | Prisma.ProductAccompanimentScalarFieldEnum;
  having?: Prisma.ProductAccompanimentScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: ProductAccompanimentCountAggregateInputType | true;
  _min?: ProductAccompanimentMinAggregateInputType;
  _max?: ProductAccompanimentMaxAggregateInputType;
};

export type ProductAccompanimentGroupByOutputType = {
  id: string;
  label: string;
  productId: string;
  _count: ProductAccompanimentCountAggregateOutputType | null;
  _min: ProductAccompanimentMinAggregateOutputType | null;
  _max: ProductAccompanimentMaxAggregateOutputType | null;
};

type GetProductAccompanimentGroupByPayload<
  T extends ProductAccompanimentGroupByArgs,
> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProductAccompanimentGroupByOutputType, T["by"]> & {
      [P in keyof T &
        keyof ProductAccompanimentGroupByOutputType]: P extends "_count"
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<T[P], ProductAccompanimentGroupByOutputType[P]>
        : Prisma.GetScalarType<T[P], ProductAccompanimentGroupByOutputType[P]>;
    }
  >
>;

export type ProductAccompanimentWhereInput = {
  AND?:
    | Prisma.ProductAccompanimentWhereInput
    | Prisma.ProductAccompanimentWhereInput[];
  OR?: Prisma.ProductAccompanimentWhereInput[];
  NOT?:
    | Prisma.ProductAccompanimentWhereInput
    | Prisma.ProductAccompanimentWhereInput[];
  id?: Prisma.StringFilter<"ProductAccompaniment"> | string;
  label?: Prisma.StringFilter<"ProductAccompaniment"> | string;
  productId?: Prisma.StringFilter<"ProductAccompaniment"> | string;
  product?: Prisma.XOR<
    Prisma.ProductScalarRelationFilter,
    Prisma.ProductWhereInput
  >;
};

export type ProductAccompanimentOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  label?: Prisma.SortOrder;
  productId?: Prisma.SortOrder;
  product?: Prisma.ProductOrderByWithRelationInput;
};

export type ProductAccompanimentWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string;
    AND?:
      | Prisma.ProductAccompanimentWhereInput
      | Prisma.ProductAccompanimentWhereInput[];
    OR?: Prisma.ProductAccompanimentWhereInput[];
    NOT?:
      | Prisma.ProductAccompanimentWhereInput
      | Prisma.ProductAccompanimentWhereInput[];
    label?: Prisma.StringFilter<"ProductAccompaniment"> | string;
    productId?: Prisma.StringFilter<"ProductAccompaniment"> | string;
    product?: Prisma.XOR<
      Prisma.ProductScalarRelationFilter,
      Prisma.ProductWhereInput
    >;
  },
  "id"
>;

export type ProductAccompanimentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  label?: Prisma.SortOrder;
  productId?: Prisma.SortOrder;
  _count?: Prisma.ProductAccompanimentCountOrderByAggregateInput;
  _max?: Prisma.ProductAccompanimentMaxOrderByAggregateInput;
  _min?: Prisma.ProductAccompanimentMinOrderByAggregateInput;
};

export type ProductAccompanimentScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.ProductAccompanimentScalarWhereWithAggregatesInput
    | Prisma.ProductAccompanimentScalarWhereWithAggregatesInput[];
  OR?: Prisma.ProductAccompanimentScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.ProductAccompanimentScalarWhereWithAggregatesInput
    | Prisma.ProductAccompanimentScalarWhereWithAggregatesInput[];
  id?: Prisma.StringWithAggregatesFilter<"ProductAccompaniment"> | string;
  label?: Prisma.StringWithAggregatesFilter<"ProductAccompaniment"> | string;
  productId?:
    | Prisma.StringWithAggregatesFilter<"ProductAccompaniment">
    | string;
};

export type ProductAccompanimentCreateInput = {
  id?: string;
  label: string;
  product: Prisma.ProductCreateNestedOneWithoutAccompanimentsInput;
};

export type ProductAccompanimentUncheckedCreateInput = {
  id?: string;
  label: string;
  productId: string;
};

export type ProductAccompanimentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  label?: Prisma.StringFieldUpdateOperationsInput | string;
  product?: Prisma.ProductUpdateOneRequiredWithoutAccompanimentsNestedInput;
};

export type ProductAccompanimentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  label?: Prisma.StringFieldUpdateOperationsInput | string;
  productId?: Prisma.StringFieldUpdateOperationsInput | string;
};

export type ProductAccompanimentCreateManyInput = {
  id?: string;
  label: string;
  productId: string;
};

export type ProductAccompanimentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  label?: Prisma.StringFieldUpdateOperationsInput | string;
};

export type ProductAccompanimentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  label?: Prisma.StringFieldUpdateOperationsInput | string;
  productId?: Prisma.StringFieldUpdateOperationsInput | string;
};

export type ProductAccompanimentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  label?: Prisma.SortOrder;
  productId?: Prisma.SortOrder;
};

export type ProductAccompanimentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  label?: Prisma.SortOrder;
  productId?: Prisma.SortOrder;
};

export type ProductAccompanimentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  label?: Prisma.SortOrder;
  productId?: Prisma.SortOrder;
};

export type ProductAccompanimentListRelationFilter = {
  every?: Prisma.ProductAccompanimentWhereInput;
  some?: Prisma.ProductAccompanimentWhereInput;
  none?: Prisma.ProductAccompanimentWhereInput;
};

export type ProductAccompanimentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type ProductAccompanimentCreateNestedManyWithoutProductInput = {
  create?:
    | Prisma.XOR<
        Prisma.ProductAccompanimentCreateWithoutProductInput,
        Prisma.ProductAccompanimentUncheckedCreateWithoutProductInput
      >
    | Prisma.ProductAccompanimentCreateWithoutProductInput[]
    | Prisma.ProductAccompanimentUncheckedCreateWithoutProductInput[];
  connectOrCreate?:
    | Prisma.ProductAccompanimentCreateOrConnectWithoutProductInput
    | Prisma.ProductAccompanimentCreateOrConnectWithoutProductInput[];
  createMany?: Prisma.ProductAccompanimentCreateManyProductInputEnvelope;
  connect?:
    | Prisma.ProductAccompanimentWhereUniqueInput
    | Prisma.ProductAccompanimentWhereUniqueInput[];
};

export type ProductAccompanimentUncheckedCreateNestedManyWithoutProductInput = {
  create?:
    | Prisma.XOR<
        Prisma.ProductAccompanimentCreateWithoutProductInput,
        Prisma.ProductAccompanimentUncheckedCreateWithoutProductInput
      >
    | Prisma.ProductAccompanimentCreateWithoutProductInput[]
    | Prisma.ProductAccompanimentUncheckedCreateWithoutProductInput[];
  connectOrCreate?:
    | Prisma.ProductAccompanimentCreateOrConnectWithoutProductInput
    | Prisma.ProductAccompanimentCreateOrConnectWithoutProductInput[];
  createMany?: Prisma.ProductAccompanimentCreateManyProductInputEnvelope;
  connect?:
    | Prisma.ProductAccompanimentWhereUniqueInput
    | Prisma.ProductAccompanimentWhereUniqueInput[];
};

export type ProductAccompanimentUpdateManyWithoutProductNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.ProductAccompanimentCreateWithoutProductInput,
        Prisma.ProductAccompanimentUncheckedCreateWithoutProductInput
      >
    | Prisma.ProductAccompanimentCreateWithoutProductInput[]
    | Prisma.ProductAccompanimentUncheckedCreateWithoutProductInput[];
  connectOrCreate?:
    | Prisma.ProductAccompanimentCreateOrConnectWithoutProductInput
    | Prisma.ProductAccompanimentCreateOrConnectWithoutProductInput[];
  upsert?:
    | Prisma.ProductAccompanimentUpsertWithWhereUniqueWithoutProductInput
    | Prisma.ProductAccompanimentUpsertWithWhereUniqueWithoutProductInput[];
  createMany?: Prisma.ProductAccompanimentCreateManyProductInputEnvelope;
  set?:
    | Prisma.ProductAccompanimentWhereUniqueInput
    | Prisma.ProductAccompanimentWhereUniqueInput[];
  disconnect?:
    | Prisma.ProductAccompanimentWhereUniqueInput
    | Prisma.ProductAccompanimentWhereUniqueInput[];
  delete?:
    | Prisma.ProductAccompanimentWhereUniqueInput
    | Prisma.ProductAccompanimentWhereUniqueInput[];
  connect?:
    | Prisma.ProductAccompanimentWhereUniqueInput
    | Prisma.ProductAccompanimentWhereUniqueInput[];
  update?:
    | Prisma.ProductAccompanimentUpdateWithWhereUniqueWithoutProductInput
    | Prisma.ProductAccompanimentUpdateWithWhereUniqueWithoutProductInput[];
  updateMany?:
    | Prisma.ProductAccompanimentUpdateManyWithWhereWithoutProductInput
    | Prisma.ProductAccompanimentUpdateManyWithWhereWithoutProductInput[];
  deleteMany?:
    | Prisma.ProductAccompanimentScalarWhereInput
    | Prisma.ProductAccompanimentScalarWhereInput[];
};

export type ProductAccompanimentUncheckedUpdateManyWithoutProductNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.ProductAccompanimentCreateWithoutProductInput,
        Prisma.ProductAccompanimentUncheckedCreateWithoutProductInput
      >
    | Prisma.ProductAccompanimentCreateWithoutProductInput[]
    | Prisma.ProductAccompanimentUncheckedCreateWithoutProductInput[];
  connectOrCreate?:
    | Prisma.ProductAccompanimentCreateOrConnectWithoutProductInput
    | Prisma.ProductAccompanimentCreateOrConnectWithoutProductInput[];
  upsert?:
    | Prisma.ProductAccompanimentUpsertWithWhereUniqueWithoutProductInput
    | Prisma.ProductAccompanimentUpsertWithWhereUniqueWithoutProductInput[];
  createMany?: Prisma.ProductAccompanimentCreateManyProductInputEnvelope;
  set?:
    | Prisma.ProductAccompanimentWhereUniqueInput
    | Prisma.ProductAccompanimentWhereUniqueInput[];
  disconnect?:
    | Prisma.ProductAccompanimentWhereUniqueInput
    | Prisma.ProductAccompanimentWhereUniqueInput[];
  delete?:
    | Prisma.ProductAccompanimentWhereUniqueInput
    | Prisma.ProductAccompanimentWhereUniqueInput[];
  connect?:
    | Prisma.ProductAccompanimentWhereUniqueInput
    | Prisma.ProductAccompanimentWhereUniqueInput[];
  update?:
    | Prisma.ProductAccompanimentUpdateWithWhereUniqueWithoutProductInput
    | Prisma.ProductAccompanimentUpdateWithWhereUniqueWithoutProductInput[];
  updateMany?:
    | Prisma.ProductAccompanimentUpdateManyWithWhereWithoutProductInput
    | Prisma.ProductAccompanimentUpdateManyWithWhereWithoutProductInput[];
  deleteMany?:
    | Prisma.ProductAccompanimentScalarWhereInput
    | Prisma.ProductAccompanimentScalarWhereInput[];
};

export type ProductAccompanimentCreateWithoutProductInput = {
  id?: string;
  label: string;
};

export type ProductAccompanimentUncheckedCreateWithoutProductInput = {
  id?: string;
  label: string;
};

export type ProductAccompanimentCreateOrConnectWithoutProductInput = {
  where: Prisma.ProductAccompanimentWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.ProductAccompanimentCreateWithoutProductInput,
    Prisma.ProductAccompanimentUncheckedCreateWithoutProductInput
  >;
};

export type ProductAccompanimentCreateManyProductInputEnvelope = {
  data:
    | Prisma.ProductAccompanimentCreateManyProductInput
    | Prisma.ProductAccompanimentCreateManyProductInput[];
  skipDuplicates?: boolean;
};

export type ProductAccompanimentUpsertWithWhereUniqueWithoutProductInput = {
  where: Prisma.ProductAccompanimentWhereUniqueInput;
  update: Prisma.XOR<
    Prisma.ProductAccompanimentUpdateWithoutProductInput,
    Prisma.ProductAccompanimentUncheckedUpdateWithoutProductInput
  >;
  create: Prisma.XOR<
    Prisma.ProductAccompanimentCreateWithoutProductInput,
    Prisma.ProductAccompanimentUncheckedCreateWithoutProductInput
  >;
};

export type ProductAccompanimentUpdateWithWhereUniqueWithoutProductInput = {
  where: Prisma.ProductAccompanimentWhereUniqueInput;
  data: Prisma.XOR<
    Prisma.ProductAccompanimentUpdateWithoutProductInput,
    Prisma.ProductAccompanimentUncheckedUpdateWithoutProductInput
  >;
};

export type ProductAccompanimentUpdateManyWithWhereWithoutProductInput = {
  where: Prisma.ProductAccompanimentScalarWhereInput;
  data: Prisma.XOR<
    Prisma.ProductAccompanimentUpdateManyMutationInput,
    Prisma.ProductAccompanimentUncheckedUpdateManyWithoutProductInput
  >;
};

export type ProductAccompanimentScalarWhereInput = {
  AND?:
    | Prisma.ProductAccompanimentScalarWhereInput
    | Prisma.ProductAccompanimentScalarWhereInput[];
  OR?: Prisma.ProductAccompanimentScalarWhereInput[];
  NOT?:
    | Prisma.ProductAccompanimentScalarWhereInput
    | Prisma.ProductAccompanimentScalarWhereInput[];
  id?: Prisma.StringFilter<"ProductAccompaniment"> | string;
  label?: Prisma.StringFilter<"ProductAccompaniment"> | string;
  productId?: Prisma.StringFilter<"ProductAccompaniment"> | string;
};

export type ProductAccompanimentCreateManyProductInput = {
  id?: string;
  label: string;
};

export type ProductAccompanimentUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  label?: Prisma.StringFieldUpdateOperationsInput | string;
};

export type ProductAccompanimentUncheckedUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  label?: Prisma.StringFieldUpdateOperationsInput | string;
};

export type ProductAccompanimentUncheckedUpdateManyWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  label?: Prisma.StringFieldUpdateOperationsInput | string;
};

export type ProductAccompanimentSelect<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    label?: boolean;
    productId?: boolean;
    product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["productAccompaniment"]
>;

export type ProductAccompanimentSelectCreateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    label?: boolean;
    productId?: boolean;
    product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["productAccompaniment"]
>;

export type ProductAccompanimentSelectUpdateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    label?: boolean;
    productId?: boolean;
    product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["productAccompaniment"]
>;

export type ProductAccompanimentSelectScalar = {
  id?: boolean;
  label?: boolean;
  productId?: boolean;
};

export type ProductAccompanimentOmit<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  "id" | "label" | "productId",
  ExtArgs["result"]["productAccompaniment"]
>;
export type ProductAccompanimentInclude<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>;
};
export type ProductAccompanimentIncludeCreateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>;
};
export type ProductAccompanimentIncludeUpdateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>;
};

export type $ProductAccompanimentPayload<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: "ProductAccompaniment";
  objects: {
    product: Prisma.$ProductPayload<ExtArgs>;
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string;
      label: string;
      productId: string;
    },
    ExtArgs["result"]["productAccompaniment"]
  >;
  composites: {};
};

export type ProductAccompanimentGetPayload<
  S extends boolean | null | undefined | ProductAccompanimentDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$ProductAccompanimentPayload, S>;

export type ProductAccompanimentCountArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<
  ProductAccompanimentFindManyArgs,
  "select" | "include" | "distinct" | "omit"
> & {
  select?: ProductAccompanimentCountAggregateInputType | true;
};

export interface ProductAccompanimentDelegate<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>["model"]["ProductAccompaniment"];
    meta: { name: "ProductAccompaniment" };
  };
  /**
   * Find zero or one ProductAccompaniment that matches the filter.
   * @param {ProductAccompanimentFindUniqueArgs} args - Arguments to find a ProductAccompaniment
   * @example
   * // Get one ProductAccompaniment
   * const productAccompaniment = await prisma.productAccompaniment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProductAccompanimentFindUniqueArgs>(
    args: Prisma.SelectSubset<T, ProductAccompanimentFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__ProductAccompanimentClient<
    runtime.Types.Result.GetResult<
      Prisma.$ProductAccompanimentPayload<ExtArgs>,
      T,
      "findUnique",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one ProductAccompaniment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProductAccompanimentFindUniqueOrThrowArgs} args - Arguments to find a ProductAccompaniment
   * @example
   * // Get one ProductAccompaniment
   * const productAccompaniment = await prisma.productAccompaniment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProductAccompanimentFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<
      T,
      ProductAccompanimentFindUniqueOrThrowArgs<ExtArgs>
    >,
  ): Prisma.Prisma__ProductAccompanimentClient<
    runtime.Types.Result.GetResult<
      Prisma.$ProductAccompanimentPayload<ExtArgs>,
      T,
      "findUniqueOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first ProductAccompaniment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductAccompanimentFindFirstArgs} args - Arguments to find a ProductAccompaniment
   * @example
   * // Get one ProductAccompaniment
   * const productAccompaniment = await prisma.productAccompaniment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProductAccompanimentFindFirstArgs>(
    args?: Prisma.SelectSubset<T, ProductAccompanimentFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__ProductAccompanimentClient<
    runtime.Types.Result.GetResult<
      Prisma.$ProductAccompanimentPayload<ExtArgs>,
      T,
      "findFirst",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first ProductAccompaniment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductAccompanimentFindFirstOrThrowArgs} args - Arguments to find a ProductAccompaniment
   * @example
   * // Get one ProductAccompaniment
   * const productAccompaniment = await prisma.productAccompaniment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProductAccompanimentFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<
      T,
      ProductAccompanimentFindFirstOrThrowArgs<ExtArgs>
    >,
  ): Prisma.Prisma__ProductAccompanimentClient<
    runtime.Types.Result.GetResult<
      Prisma.$ProductAccompanimentPayload<ExtArgs>,
      T,
      "findFirstOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more ProductAccompaniments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductAccompanimentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProductAccompaniments
   * const productAccompaniments = await prisma.productAccompaniment.findMany()
   *
   * // Get first 10 ProductAccompaniments
   * const productAccompaniments = await prisma.productAccompaniment.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const productAccompanimentWithIdOnly = await prisma.productAccompaniment.findMany({ select: { id: true } })
   *
   */
  findMany<T extends ProductAccompanimentFindManyArgs>(
    args?: Prisma.SelectSubset<T, ProductAccompanimentFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$ProductAccompanimentPayload<ExtArgs>,
      T,
      "findMany",
      GlobalOmitOptions
    >
  >;

  /**
   * Create a ProductAccompaniment.
   * @param {ProductAccompanimentCreateArgs} args - Arguments to create a ProductAccompaniment.
   * @example
   * // Create one ProductAccompaniment
   * const ProductAccompaniment = await prisma.productAccompaniment.create({
   *   data: {
   *     // ... data to create a ProductAccompaniment
   *   }
   * })
   *
   */
  create<T extends ProductAccompanimentCreateArgs>(
    args: Prisma.SelectSubset<T, ProductAccompanimentCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__ProductAccompanimentClient<
    runtime.Types.Result.GetResult<
      Prisma.$ProductAccompanimentPayload<ExtArgs>,
      T,
      "create",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many ProductAccompaniments.
   * @param {ProductAccompanimentCreateManyArgs} args - Arguments to create many ProductAccompaniments.
   * @example
   * // Create many ProductAccompaniments
   * const productAccompaniment = await prisma.productAccompaniment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends ProductAccompanimentCreateManyArgs>(
    args?: Prisma.SelectSubset<T, ProductAccompanimentCreateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many ProductAccompaniments and returns the data saved in the database.
   * @param {ProductAccompanimentCreateManyAndReturnArgs} args - Arguments to create many ProductAccompaniments.
   * @example
   * // Create many ProductAccompaniments
   * const productAccompaniment = await prisma.productAccompaniment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many ProductAccompaniments and only return the `id`
   * const productAccompanimentWithIdOnly = await prisma.productAccompaniment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends ProductAccompanimentCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<
      T,
      ProductAccompanimentCreateManyAndReturnArgs<ExtArgs>
    >,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$ProductAccompanimentPayload<ExtArgs>,
      T,
      "createManyAndReturn",
      GlobalOmitOptions
    >
  >;

  /**
   * Delete a ProductAccompaniment.
   * @param {ProductAccompanimentDeleteArgs} args - Arguments to delete one ProductAccompaniment.
   * @example
   * // Delete one ProductAccompaniment
   * const ProductAccompaniment = await prisma.productAccompaniment.delete({
   *   where: {
   *     // ... filter to delete one ProductAccompaniment
   *   }
   * })
   *
   */
  delete<T extends ProductAccompanimentDeleteArgs>(
    args: Prisma.SelectSubset<T, ProductAccompanimentDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__ProductAccompanimentClient<
    runtime.Types.Result.GetResult<
      Prisma.$ProductAccompanimentPayload<ExtArgs>,
      T,
      "delete",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one ProductAccompaniment.
   * @param {ProductAccompanimentUpdateArgs} args - Arguments to update one ProductAccompaniment.
   * @example
   * // Update one ProductAccompaniment
   * const productAccompaniment = await prisma.productAccompaniment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends ProductAccompanimentUpdateArgs>(
    args: Prisma.SelectSubset<T, ProductAccompanimentUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__ProductAccompanimentClient<
    runtime.Types.Result.GetResult<
      Prisma.$ProductAccompanimentPayload<ExtArgs>,
      T,
      "update",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more ProductAccompaniments.
   * @param {ProductAccompanimentDeleteManyArgs} args - Arguments to filter ProductAccompaniments to delete.
   * @example
   * // Delete a few ProductAccompaniments
   * const { count } = await prisma.productAccompaniment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends ProductAccompanimentDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, ProductAccompanimentDeleteManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more ProductAccompaniments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductAccompanimentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProductAccompaniments
   * const productAccompaniment = await prisma.productAccompaniment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends ProductAccompanimentUpdateManyArgs>(
    args: Prisma.SelectSubset<T, ProductAccompanimentUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more ProductAccompaniments and returns the data updated in the database.
   * @param {ProductAccompanimentUpdateManyAndReturnArgs} args - Arguments to update many ProductAccompaniments.
   * @example
   * // Update many ProductAccompaniments
   * const productAccompaniment = await prisma.productAccompaniment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more ProductAccompaniments and only return the `id`
   * const productAccompanimentWithIdOnly = await prisma.productAccompaniment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends ProductAccompanimentUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<
      T,
      ProductAccompanimentUpdateManyAndReturnArgs<ExtArgs>
    >,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$ProductAccompanimentPayload<ExtArgs>,
      T,
      "updateManyAndReturn",
      GlobalOmitOptions
    >
  >;

  /**
   * Create or update one ProductAccompaniment.
   * @param {ProductAccompanimentUpsertArgs} args - Arguments to update or create a ProductAccompaniment.
   * @example
   * // Update or create a ProductAccompaniment
   * const productAccompaniment = await prisma.productAccompaniment.upsert({
   *   create: {
   *     // ... data to create a ProductAccompaniment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProductAccompaniment we want to update
   *   }
   * })
   */
  upsert<T extends ProductAccompanimentUpsertArgs>(
    args: Prisma.SelectSubset<T, ProductAccompanimentUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__ProductAccompanimentClient<
    runtime.Types.Result.GetResult<
      Prisma.$ProductAccompanimentPayload<ExtArgs>,
      T,
      "upsert",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of ProductAccompaniments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductAccompanimentCountArgs} args - Arguments to filter ProductAccompaniments to count.
   * @example
   * // Count the number of ProductAccompaniments
   * const count = await prisma.productAccompaniment.count({
   *   where: {
   *     // ... the filter for the ProductAccompaniments we want to count
   *   }
   * })
   **/
  count<T extends ProductAccompanimentCountArgs>(
    args?: Prisma.Subset<T, ProductAccompanimentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<"select", any>
      ? T["select"] extends true
        ? number
        : Prisma.GetScalarType<
            T["select"],
            ProductAccompanimentCountAggregateOutputType
          >
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a ProductAccompaniment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductAccompanimentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends ProductAccompanimentAggregateArgs>(
    args: Prisma.Subset<T, ProductAccompanimentAggregateArgs>,
  ): Prisma.PrismaPromise<GetProductAccompanimentAggregateType<T>>;

  /**
   * Group by ProductAccompaniment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductAccompanimentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends ProductAccompanimentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<"skip", Prisma.Keys<T>>,
      Prisma.Extends<"take", Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProductAccompanimentGroupByArgs["orderBy"] }
      : { orderBy?: ProductAccompanimentGroupByArgs["orderBy"] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T["having"]>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    "Field ",
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ];
          }[HavingFields]
        : "take" extends Prisma.Keys<T>
          ? "orderBy" extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : "skip" extends Prisma.Keys<T>
            ? "orderBy" extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<
      T,
      ProductAccompanimentGroupByArgs,
      OrderByArg
    > &
      InputErrors,
  ): {} extends InputErrors
    ? GetProductAccompanimentGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the ProductAccompaniment model
   */
  readonly fields: ProductAccompanimentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProductAccompaniment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProductAccompanimentClient<
  T,
  Null = never,
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise";
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>,
  ): Prisma.Prisma__ProductClient<
    | runtime.Types.Result.GetResult<
        Prisma.$ProductPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the ProductAccompaniment model
 */
export interface ProductAccompanimentFieldRefs {
  readonly id: Prisma.FieldRef<"ProductAccompaniment", "String">;
  readonly label: Prisma.FieldRef<"ProductAccompaniment", "String">;
  readonly productId: Prisma.FieldRef<"ProductAccompaniment", "String">;
}

// Custom InputTypes
/**
 * ProductAccompaniment findUnique
 */
export type ProductAccompanimentFindUniqueArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ProductAccompaniment
   */
  select?: Prisma.ProductAccompanimentSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ProductAccompaniment
   */
  omit?: Prisma.ProductAccompanimentOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductAccompanimentInclude<ExtArgs> | null;
  /**
   * Filter, which ProductAccompaniment to fetch.
   */
  where: Prisma.ProductAccompanimentWhereUniqueInput;
};

/**
 * ProductAccompaniment findUniqueOrThrow
 */
export type ProductAccompanimentFindUniqueOrThrowArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ProductAccompaniment
   */
  select?: Prisma.ProductAccompanimentSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ProductAccompaniment
   */
  omit?: Prisma.ProductAccompanimentOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductAccompanimentInclude<ExtArgs> | null;
  /**
   * Filter, which ProductAccompaniment to fetch.
   */
  where: Prisma.ProductAccompanimentWhereUniqueInput;
};

/**
 * ProductAccompaniment findFirst
 */
export type ProductAccompanimentFindFirstArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ProductAccompaniment
   */
  select?: Prisma.ProductAccompanimentSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ProductAccompaniment
   */
  omit?: Prisma.ProductAccompanimentOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductAccompanimentInclude<ExtArgs> | null;
  /**
   * Filter, which ProductAccompaniment to fetch.
   */
  where?: Prisma.ProductAccompanimentWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ProductAccompaniments to fetch.
   */
  orderBy?:
    | Prisma.ProductAccompanimentOrderByWithRelationInput
    | Prisma.ProductAccompanimentOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for ProductAccompaniments.
   */
  cursor?: Prisma.ProductAccompanimentWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ProductAccompaniments from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ProductAccompaniments.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ProductAccompaniments.
   */
  distinct?:
    | Prisma.ProductAccompanimentScalarFieldEnum
    | Prisma.ProductAccompanimentScalarFieldEnum[];
};

/**
 * ProductAccompaniment findFirstOrThrow
 */
export type ProductAccompanimentFindFirstOrThrowArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ProductAccompaniment
   */
  select?: Prisma.ProductAccompanimentSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ProductAccompaniment
   */
  omit?: Prisma.ProductAccompanimentOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductAccompanimentInclude<ExtArgs> | null;
  /**
   * Filter, which ProductAccompaniment to fetch.
   */
  where?: Prisma.ProductAccompanimentWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ProductAccompaniments to fetch.
   */
  orderBy?:
    | Prisma.ProductAccompanimentOrderByWithRelationInput
    | Prisma.ProductAccompanimentOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for ProductAccompaniments.
   */
  cursor?: Prisma.ProductAccompanimentWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ProductAccompaniments from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ProductAccompaniments.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ProductAccompaniments.
   */
  distinct?:
    | Prisma.ProductAccompanimentScalarFieldEnum
    | Prisma.ProductAccompanimentScalarFieldEnum[];
};

/**
 * ProductAccompaniment findMany
 */
export type ProductAccompanimentFindManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ProductAccompaniment
   */
  select?: Prisma.ProductAccompanimentSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ProductAccompaniment
   */
  omit?: Prisma.ProductAccompanimentOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductAccompanimentInclude<ExtArgs> | null;
  /**
   * Filter, which ProductAccompaniments to fetch.
   */
  where?: Prisma.ProductAccompanimentWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ProductAccompaniments to fetch.
   */
  orderBy?:
    | Prisma.ProductAccompanimentOrderByWithRelationInput
    | Prisma.ProductAccompanimentOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing ProductAccompaniments.
   */
  cursor?: Prisma.ProductAccompanimentWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ProductAccompaniments from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ProductAccompaniments.
   */
  skip?: number;
  distinct?:
    | Prisma.ProductAccompanimentScalarFieldEnum
    | Prisma.ProductAccompanimentScalarFieldEnum[];
};

/**
 * ProductAccompaniment create
 */
export type ProductAccompanimentCreateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ProductAccompaniment
   */
  select?: Prisma.ProductAccompanimentSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ProductAccompaniment
   */
  omit?: Prisma.ProductAccompanimentOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductAccompanimentInclude<ExtArgs> | null;
  /**
   * The data needed to create a ProductAccompaniment.
   */
  data: Prisma.XOR<
    Prisma.ProductAccompanimentCreateInput,
    Prisma.ProductAccompanimentUncheckedCreateInput
  >;
};

/**
 * ProductAccompaniment createMany
 */
export type ProductAccompanimentCreateManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many ProductAccompaniments.
   */
  data:
    | Prisma.ProductAccompanimentCreateManyInput
    | Prisma.ProductAccompanimentCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * ProductAccompaniment createManyAndReturn
 */
export type ProductAccompanimentCreateManyAndReturnArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ProductAccompaniment
   */
  select?: Prisma.ProductAccompanimentSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the ProductAccompaniment
   */
  omit?: Prisma.ProductAccompanimentOmit<ExtArgs> | null;
  /**
   * The data used to create many ProductAccompaniments.
   */
  data:
    | Prisma.ProductAccompanimentCreateManyInput
    | Prisma.ProductAccompanimentCreateManyInput[];
  skipDuplicates?: boolean;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductAccompanimentIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * ProductAccompaniment update
 */
export type ProductAccompanimentUpdateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ProductAccompaniment
   */
  select?: Prisma.ProductAccompanimentSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ProductAccompaniment
   */
  omit?: Prisma.ProductAccompanimentOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductAccompanimentInclude<ExtArgs> | null;
  /**
   * The data needed to update a ProductAccompaniment.
   */
  data: Prisma.XOR<
    Prisma.ProductAccompanimentUpdateInput,
    Prisma.ProductAccompanimentUncheckedUpdateInput
  >;
  /**
   * Choose, which ProductAccompaniment to update.
   */
  where: Prisma.ProductAccompanimentWhereUniqueInput;
};

/**
 * ProductAccompaniment updateMany
 */
export type ProductAccompanimentUpdateManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update ProductAccompaniments.
   */
  data: Prisma.XOR<
    Prisma.ProductAccompanimentUpdateManyMutationInput,
    Prisma.ProductAccompanimentUncheckedUpdateManyInput
  >;
  /**
   * Filter which ProductAccompaniments to update
   */
  where?: Prisma.ProductAccompanimentWhereInput;
  /**
   * Limit how many ProductAccompaniments to update.
   */
  limit?: number;
};

/**
 * ProductAccompaniment updateManyAndReturn
 */
export type ProductAccompanimentUpdateManyAndReturnArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ProductAccompaniment
   */
  select?: Prisma.ProductAccompanimentSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the ProductAccompaniment
   */
  omit?: Prisma.ProductAccompanimentOmit<ExtArgs> | null;
  /**
   * The data used to update ProductAccompaniments.
   */
  data: Prisma.XOR<
    Prisma.ProductAccompanimentUpdateManyMutationInput,
    Prisma.ProductAccompanimentUncheckedUpdateManyInput
  >;
  /**
   * Filter which ProductAccompaniments to update
   */
  where?: Prisma.ProductAccompanimentWhereInput;
  /**
   * Limit how many ProductAccompaniments to update.
   */
  limit?: number;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductAccompanimentIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * ProductAccompaniment upsert
 */
export type ProductAccompanimentUpsertArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ProductAccompaniment
   */
  select?: Prisma.ProductAccompanimentSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ProductAccompaniment
   */
  omit?: Prisma.ProductAccompanimentOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductAccompanimentInclude<ExtArgs> | null;
  /**
   * The filter to search for the ProductAccompaniment to update in case it exists.
   */
  where: Prisma.ProductAccompanimentWhereUniqueInput;
  /**
   * In case the ProductAccompaniment found by the `where` argument doesn't exist, create a new ProductAccompaniment with this data.
   */
  create: Prisma.XOR<
    Prisma.ProductAccompanimentCreateInput,
    Prisma.ProductAccompanimentUncheckedCreateInput
  >;
  /**
   * In case the ProductAccompaniment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.ProductAccompanimentUpdateInput,
    Prisma.ProductAccompanimentUncheckedUpdateInput
  >;
};

/**
 * ProductAccompaniment delete
 */
export type ProductAccompanimentDeleteArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ProductAccompaniment
   */
  select?: Prisma.ProductAccompanimentSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ProductAccompaniment
   */
  omit?: Prisma.ProductAccompanimentOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductAccompanimentInclude<ExtArgs> | null;
  /**
   * Filter which ProductAccompaniment to delete.
   */
  where: Prisma.ProductAccompanimentWhereUniqueInput;
};

/**
 * ProductAccompaniment deleteMany
 */
export type ProductAccompanimentDeleteManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which ProductAccompaniments to delete
   */
  where?: Prisma.ProductAccompanimentWhereInput;
  /**
   * Limit how many ProductAccompaniments to delete.
   */
  limit?: number;
};

/**
 * ProductAccompaniment without action
 */
export type ProductAccompanimentDefaultArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ProductAccompaniment
   */
  select?: Prisma.ProductAccompanimentSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ProductAccompaniment
   */
  omit?: Prisma.ProductAccompanimentOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductAccompanimentInclude<ExtArgs> | null;
};
