/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck
/*
 * This file exports the `UserFavoriteRestaurant` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library";
import type * as $Enums from "../enums";
import type * as Prisma from "../internal/prismaNamespace";

/**
 * Model UserFavoriteRestaurant
 *
 */
export type UserFavoriteRestaurantModel =
  runtime.Types.Result.DefaultSelection<Prisma.$UserFavoriteRestaurantPayload>;

export type AggregateUserFavoriteRestaurant = {
  _count: UserFavoriteRestaurantCountAggregateOutputType | null;
  _min: UserFavoriteRestaurantMinAggregateOutputType | null;
  _max: UserFavoriteRestaurantMaxAggregateOutputType | null;
};

export type UserFavoriteRestaurantMinAggregateOutputType = {
  userId: string | null;
  restaurantId: string | null;
  createdAt: Date | null;
};

export type UserFavoriteRestaurantMaxAggregateOutputType = {
  userId: string | null;
  restaurantId: string | null;
  createdAt: Date | null;
};

export type UserFavoriteRestaurantCountAggregateOutputType = {
  userId: number;
  restaurantId: number;
  createdAt: number;
  _all: number;
};

export type UserFavoriteRestaurantMinAggregateInputType = {
  userId?: true;
  restaurantId?: true;
  createdAt?: true;
};

export type UserFavoriteRestaurantMaxAggregateInputType = {
  userId?: true;
  restaurantId?: true;
  createdAt?: true;
};

export type UserFavoriteRestaurantCountAggregateInputType = {
  userId?: true;
  restaurantId?: true;
  createdAt?: true;
  _all?: true;
};

export type UserFavoriteRestaurantAggregateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which UserFavoriteRestaurant to aggregate.
   */
  where?: Prisma.UserFavoriteRestaurantWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of UserFavoriteRestaurants to fetch.
   */
  orderBy?:
    | Prisma.UserFavoriteRestaurantOrderByWithRelationInput
    | Prisma.UserFavoriteRestaurantOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.UserFavoriteRestaurantWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` UserFavoriteRestaurants from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` UserFavoriteRestaurants.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned UserFavoriteRestaurants
   **/
  _count?: true | UserFavoriteRestaurantCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: UserFavoriteRestaurantMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: UserFavoriteRestaurantMaxAggregateInputType;
};

export type GetUserFavoriteRestaurantAggregateType<
  T extends UserFavoriteRestaurantAggregateArgs,
> = {
  [P in keyof T & keyof AggregateUserFavoriteRestaurant]: P extends
    | "_count"
    | "count"
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserFavoriteRestaurant[P]>
    : Prisma.GetScalarType<T[P], AggregateUserFavoriteRestaurant[P]>;
};

export type UserFavoriteRestaurantGroupByArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.UserFavoriteRestaurantWhereInput;
  orderBy?:
    | Prisma.UserFavoriteRestaurantOrderByWithAggregationInput
    | Prisma.UserFavoriteRestaurantOrderByWithAggregationInput[];
  by:
    | Prisma.UserFavoriteRestaurantScalarFieldEnum[]
    | Prisma.UserFavoriteRestaurantScalarFieldEnum;
  having?: Prisma.UserFavoriteRestaurantScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: UserFavoriteRestaurantCountAggregateInputType | true;
  _min?: UserFavoriteRestaurantMinAggregateInputType;
  _max?: UserFavoriteRestaurantMaxAggregateInputType;
};

export type UserFavoriteRestaurantGroupByOutputType = {
  userId: string;
  restaurantId: string;
  createdAt: Date;
  _count: UserFavoriteRestaurantCountAggregateOutputType | null;
  _min: UserFavoriteRestaurantMinAggregateOutputType | null;
  _max: UserFavoriteRestaurantMaxAggregateOutputType | null;
};

type GetUserFavoriteRestaurantGroupByPayload<
  T extends UserFavoriteRestaurantGroupByArgs,
> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserFavoriteRestaurantGroupByOutputType, T["by"]> & {
      [P in keyof T &
        keyof UserFavoriteRestaurantGroupByOutputType]: P extends "_count"
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<
              T[P],
              UserFavoriteRestaurantGroupByOutputType[P]
            >
        : Prisma.GetScalarType<
            T[P],
            UserFavoriteRestaurantGroupByOutputType[P]
          >;
    }
  >
>;

export type UserFavoriteRestaurantWhereInput = {
  AND?:
    | Prisma.UserFavoriteRestaurantWhereInput
    | Prisma.UserFavoriteRestaurantWhereInput[];
  OR?: Prisma.UserFavoriteRestaurantWhereInput[];
  NOT?:
    | Prisma.UserFavoriteRestaurantWhereInput
    | Prisma.UserFavoriteRestaurantWhereInput[];
  userId?: Prisma.StringFilter<"UserFavoriteRestaurant"> | string;
  restaurantId?: Prisma.StringFilter<"UserFavoriteRestaurant"> | string;
  createdAt?: Prisma.DateTimeFilter<"UserFavoriteRestaurant"> | Date | string;
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
  restaurant?: Prisma.XOR<
    Prisma.RestaurantScalarRelationFilter,
    Prisma.RestaurantWhereInput
  >;
};

export type UserFavoriteRestaurantOrderByWithRelationInput = {
  userId?: Prisma.SortOrder;
  restaurantId?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  user?: Prisma.UserOrderByWithRelationInput;
  restaurant?: Prisma.RestaurantOrderByWithRelationInput;
};

export type UserFavoriteRestaurantWhereUniqueInput = Prisma.AtLeast<
  {
    userId_restaurantId?: Prisma.UserFavoriteRestaurantUserIdRestaurantIdCompoundUniqueInput;
    AND?:
      | Prisma.UserFavoriteRestaurantWhereInput
      | Prisma.UserFavoriteRestaurantWhereInput[];
    OR?: Prisma.UserFavoriteRestaurantWhereInput[];
    NOT?:
      | Prisma.UserFavoriteRestaurantWhereInput
      | Prisma.UserFavoriteRestaurantWhereInput[];
    userId?: Prisma.StringFilter<"UserFavoriteRestaurant"> | string;
    restaurantId?: Prisma.StringFilter<"UserFavoriteRestaurant"> | string;
    createdAt?: Prisma.DateTimeFilter<"UserFavoriteRestaurant"> | Date | string;
    user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
    restaurant?: Prisma.XOR<
      Prisma.RestaurantScalarRelationFilter,
      Prisma.RestaurantWhereInput
    >;
  },
  "userId_restaurantId"
>;

export type UserFavoriteRestaurantOrderByWithAggregationInput = {
  userId?: Prisma.SortOrder;
  restaurantId?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  _count?: Prisma.UserFavoriteRestaurantCountOrderByAggregateInput;
  _max?: Prisma.UserFavoriteRestaurantMaxOrderByAggregateInput;
  _min?: Prisma.UserFavoriteRestaurantMinOrderByAggregateInput;
};

export type UserFavoriteRestaurantScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.UserFavoriteRestaurantScalarWhereWithAggregatesInput
    | Prisma.UserFavoriteRestaurantScalarWhereWithAggregatesInput[];
  OR?: Prisma.UserFavoriteRestaurantScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.UserFavoriteRestaurantScalarWhereWithAggregatesInput
    | Prisma.UserFavoriteRestaurantScalarWhereWithAggregatesInput[];
  userId?: Prisma.StringWithAggregatesFilter<"UserFavoriteRestaurant"> | string;
  restaurantId?:
    | Prisma.StringWithAggregatesFilter<"UserFavoriteRestaurant">
    | string;
  createdAt?:
    | Prisma.DateTimeWithAggregatesFilter<"UserFavoriteRestaurant">
    | Date
    | string;
};

export type UserFavoriteRestaurantCreateInput = {
  createdAt?: Date | string;
  user: Prisma.UserCreateNestedOneWithoutFavoriteRestaurantsInput;
  restaurant: Prisma.RestaurantCreateNestedOneWithoutUsersWhoFavoritedInput;
};

export type UserFavoriteRestaurantUncheckedCreateInput = {
  userId: string;
  restaurantId: string;
  createdAt?: Date | string;
};

export type UserFavoriteRestaurantUpdateInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  user?: Prisma.UserUpdateOneRequiredWithoutFavoriteRestaurantsNestedInput;
  restaurant?: Prisma.RestaurantUpdateOneRequiredWithoutUsersWhoFavoritedNestedInput;
};

export type UserFavoriteRestaurantUncheckedUpdateInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  restaurantId?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type UserFavoriteRestaurantCreateManyInput = {
  userId: string;
  restaurantId: string;
  createdAt?: Date | string;
};

export type UserFavoriteRestaurantUpdateManyMutationInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type UserFavoriteRestaurantUncheckedUpdateManyInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  restaurantId?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type UserFavoriteRestaurantListRelationFilter = {
  every?: Prisma.UserFavoriteRestaurantWhereInput;
  some?: Prisma.UserFavoriteRestaurantWhereInput;
  none?: Prisma.UserFavoriteRestaurantWhereInput;
};

export type UserFavoriteRestaurantOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type UserFavoriteRestaurantUserIdRestaurantIdCompoundUniqueInput = {
  userId: string;
  restaurantId: string;
};

export type UserFavoriteRestaurantCountOrderByAggregateInput = {
  userId?: Prisma.SortOrder;
  restaurantId?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
};

export type UserFavoriteRestaurantMaxOrderByAggregateInput = {
  userId?: Prisma.SortOrder;
  restaurantId?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
};

export type UserFavoriteRestaurantMinOrderByAggregateInput = {
  userId?: Prisma.SortOrder;
  restaurantId?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
};

export type UserFavoriteRestaurantCreateNestedManyWithoutUserInput = {
  create?:
    | Prisma.XOR<
        Prisma.UserFavoriteRestaurantCreateWithoutUserInput,
        Prisma.UserFavoriteRestaurantUncheckedCreateWithoutUserInput
      >
    | Prisma.UserFavoriteRestaurantCreateWithoutUserInput[]
    | Prisma.UserFavoriteRestaurantUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.UserFavoriteRestaurantCreateOrConnectWithoutUserInput
    | Prisma.UserFavoriteRestaurantCreateOrConnectWithoutUserInput[];
  createMany?: Prisma.UserFavoriteRestaurantCreateManyUserInputEnvelope;
  connect?:
    | Prisma.UserFavoriteRestaurantWhereUniqueInput
    | Prisma.UserFavoriteRestaurantWhereUniqueInput[];
};

export type UserFavoriteRestaurantUncheckedCreateNestedManyWithoutUserInput = {
  create?:
    | Prisma.XOR<
        Prisma.UserFavoriteRestaurantCreateWithoutUserInput,
        Prisma.UserFavoriteRestaurantUncheckedCreateWithoutUserInput
      >
    | Prisma.UserFavoriteRestaurantCreateWithoutUserInput[]
    | Prisma.UserFavoriteRestaurantUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.UserFavoriteRestaurantCreateOrConnectWithoutUserInput
    | Prisma.UserFavoriteRestaurantCreateOrConnectWithoutUserInput[];
  createMany?: Prisma.UserFavoriteRestaurantCreateManyUserInputEnvelope;
  connect?:
    | Prisma.UserFavoriteRestaurantWhereUniqueInput
    | Prisma.UserFavoriteRestaurantWhereUniqueInput[];
};

export type UserFavoriteRestaurantUpdateManyWithoutUserNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.UserFavoriteRestaurantCreateWithoutUserInput,
        Prisma.UserFavoriteRestaurantUncheckedCreateWithoutUserInput
      >
    | Prisma.UserFavoriteRestaurantCreateWithoutUserInput[]
    | Prisma.UserFavoriteRestaurantUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.UserFavoriteRestaurantCreateOrConnectWithoutUserInput
    | Prisma.UserFavoriteRestaurantCreateOrConnectWithoutUserInput[];
  upsert?:
    | Prisma.UserFavoriteRestaurantUpsertWithWhereUniqueWithoutUserInput
    | Prisma.UserFavoriteRestaurantUpsertWithWhereUniqueWithoutUserInput[];
  createMany?: Prisma.UserFavoriteRestaurantCreateManyUserInputEnvelope;
  set?:
    | Prisma.UserFavoriteRestaurantWhereUniqueInput
    | Prisma.UserFavoriteRestaurantWhereUniqueInput[];
  disconnect?:
    | Prisma.UserFavoriteRestaurantWhereUniqueInput
    | Prisma.UserFavoriteRestaurantWhereUniqueInput[];
  delete?:
    | Prisma.UserFavoriteRestaurantWhereUniqueInput
    | Prisma.UserFavoriteRestaurantWhereUniqueInput[];
  connect?:
    | Prisma.UserFavoriteRestaurantWhereUniqueInput
    | Prisma.UserFavoriteRestaurantWhereUniqueInput[];
  update?:
    | Prisma.UserFavoriteRestaurantUpdateWithWhereUniqueWithoutUserInput
    | Prisma.UserFavoriteRestaurantUpdateWithWhereUniqueWithoutUserInput[];
  updateMany?:
    | Prisma.UserFavoriteRestaurantUpdateManyWithWhereWithoutUserInput
    | Prisma.UserFavoriteRestaurantUpdateManyWithWhereWithoutUserInput[];
  deleteMany?:
    | Prisma.UserFavoriteRestaurantScalarWhereInput
    | Prisma.UserFavoriteRestaurantScalarWhereInput[];
};

export type UserFavoriteRestaurantUncheckedUpdateManyWithoutUserNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.UserFavoriteRestaurantCreateWithoutUserInput,
        Prisma.UserFavoriteRestaurantUncheckedCreateWithoutUserInput
      >
    | Prisma.UserFavoriteRestaurantCreateWithoutUserInput[]
    | Prisma.UserFavoriteRestaurantUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.UserFavoriteRestaurantCreateOrConnectWithoutUserInput
    | Prisma.UserFavoriteRestaurantCreateOrConnectWithoutUserInput[];
  upsert?:
    | Prisma.UserFavoriteRestaurantUpsertWithWhereUniqueWithoutUserInput
    | Prisma.UserFavoriteRestaurantUpsertWithWhereUniqueWithoutUserInput[];
  createMany?: Prisma.UserFavoriteRestaurantCreateManyUserInputEnvelope;
  set?:
    | Prisma.UserFavoriteRestaurantWhereUniqueInput
    | Prisma.UserFavoriteRestaurantWhereUniqueInput[];
  disconnect?:
    | Prisma.UserFavoriteRestaurantWhereUniqueInput
    | Prisma.UserFavoriteRestaurantWhereUniqueInput[];
  delete?:
    | Prisma.UserFavoriteRestaurantWhereUniqueInput
    | Prisma.UserFavoriteRestaurantWhereUniqueInput[];
  connect?:
    | Prisma.UserFavoriteRestaurantWhereUniqueInput
    | Prisma.UserFavoriteRestaurantWhereUniqueInput[];
  update?:
    | Prisma.UserFavoriteRestaurantUpdateWithWhereUniqueWithoutUserInput
    | Prisma.UserFavoriteRestaurantUpdateWithWhereUniqueWithoutUserInput[];
  updateMany?:
    | Prisma.UserFavoriteRestaurantUpdateManyWithWhereWithoutUserInput
    | Prisma.UserFavoriteRestaurantUpdateManyWithWhereWithoutUserInput[];
  deleteMany?:
    | Prisma.UserFavoriteRestaurantScalarWhereInput
    | Prisma.UserFavoriteRestaurantScalarWhereInput[];
};

export type UserFavoriteRestaurantCreateNestedManyWithoutRestaurantInput = {
  create?:
    | Prisma.XOR<
        Prisma.UserFavoriteRestaurantCreateWithoutRestaurantInput,
        Prisma.UserFavoriteRestaurantUncheckedCreateWithoutRestaurantInput
      >
    | Prisma.UserFavoriteRestaurantCreateWithoutRestaurantInput[]
    | Prisma.UserFavoriteRestaurantUncheckedCreateWithoutRestaurantInput[];
  connectOrCreate?:
    | Prisma.UserFavoriteRestaurantCreateOrConnectWithoutRestaurantInput
    | Prisma.UserFavoriteRestaurantCreateOrConnectWithoutRestaurantInput[];
  createMany?: Prisma.UserFavoriteRestaurantCreateManyRestaurantInputEnvelope;
  connect?:
    | Prisma.UserFavoriteRestaurantWhereUniqueInput
    | Prisma.UserFavoriteRestaurantWhereUniqueInput[];
};

export type UserFavoriteRestaurantUncheckedCreateNestedManyWithoutRestaurantInput =
  {
    create?:
      | Prisma.XOR<
          Prisma.UserFavoriteRestaurantCreateWithoutRestaurantInput,
          Prisma.UserFavoriteRestaurantUncheckedCreateWithoutRestaurantInput
        >
      | Prisma.UserFavoriteRestaurantCreateWithoutRestaurantInput[]
      | Prisma.UserFavoriteRestaurantUncheckedCreateWithoutRestaurantInput[];
    connectOrCreate?:
      | Prisma.UserFavoriteRestaurantCreateOrConnectWithoutRestaurantInput
      | Prisma.UserFavoriteRestaurantCreateOrConnectWithoutRestaurantInput[];
    createMany?: Prisma.UserFavoriteRestaurantCreateManyRestaurantInputEnvelope;
    connect?:
      | Prisma.UserFavoriteRestaurantWhereUniqueInput
      | Prisma.UserFavoriteRestaurantWhereUniqueInput[];
  };

export type UserFavoriteRestaurantUpdateManyWithoutRestaurantNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.UserFavoriteRestaurantCreateWithoutRestaurantInput,
        Prisma.UserFavoriteRestaurantUncheckedCreateWithoutRestaurantInput
      >
    | Prisma.UserFavoriteRestaurantCreateWithoutRestaurantInput[]
    | Prisma.UserFavoriteRestaurantUncheckedCreateWithoutRestaurantInput[];
  connectOrCreate?:
    | Prisma.UserFavoriteRestaurantCreateOrConnectWithoutRestaurantInput
    | Prisma.UserFavoriteRestaurantCreateOrConnectWithoutRestaurantInput[];
  upsert?:
    | Prisma.UserFavoriteRestaurantUpsertWithWhereUniqueWithoutRestaurantInput
    | Prisma.UserFavoriteRestaurantUpsertWithWhereUniqueWithoutRestaurantInput[];
  createMany?: Prisma.UserFavoriteRestaurantCreateManyRestaurantInputEnvelope;
  set?:
    | Prisma.UserFavoriteRestaurantWhereUniqueInput
    | Prisma.UserFavoriteRestaurantWhereUniqueInput[];
  disconnect?:
    | Prisma.UserFavoriteRestaurantWhereUniqueInput
    | Prisma.UserFavoriteRestaurantWhereUniqueInput[];
  delete?:
    | Prisma.UserFavoriteRestaurantWhereUniqueInput
    | Prisma.UserFavoriteRestaurantWhereUniqueInput[];
  connect?:
    | Prisma.UserFavoriteRestaurantWhereUniqueInput
    | Prisma.UserFavoriteRestaurantWhereUniqueInput[];
  update?:
    | Prisma.UserFavoriteRestaurantUpdateWithWhereUniqueWithoutRestaurantInput
    | Prisma.UserFavoriteRestaurantUpdateWithWhereUniqueWithoutRestaurantInput[];
  updateMany?:
    | Prisma.UserFavoriteRestaurantUpdateManyWithWhereWithoutRestaurantInput
    | Prisma.UserFavoriteRestaurantUpdateManyWithWhereWithoutRestaurantInput[];
  deleteMany?:
    | Prisma.UserFavoriteRestaurantScalarWhereInput
    | Prisma.UserFavoriteRestaurantScalarWhereInput[];
};

export type UserFavoriteRestaurantUncheckedUpdateManyWithoutRestaurantNestedInput =
  {
    create?:
      | Prisma.XOR<
          Prisma.UserFavoriteRestaurantCreateWithoutRestaurantInput,
          Prisma.UserFavoriteRestaurantUncheckedCreateWithoutRestaurantInput
        >
      | Prisma.UserFavoriteRestaurantCreateWithoutRestaurantInput[]
      | Prisma.UserFavoriteRestaurantUncheckedCreateWithoutRestaurantInput[];
    connectOrCreate?:
      | Prisma.UserFavoriteRestaurantCreateOrConnectWithoutRestaurantInput
      | Prisma.UserFavoriteRestaurantCreateOrConnectWithoutRestaurantInput[];
    upsert?:
      | Prisma.UserFavoriteRestaurantUpsertWithWhereUniqueWithoutRestaurantInput
      | Prisma.UserFavoriteRestaurantUpsertWithWhereUniqueWithoutRestaurantInput[];
    createMany?: Prisma.UserFavoriteRestaurantCreateManyRestaurantInputEnvelope;
    set?:
      | Prisma.UserFavoriteRestaurantWhereUniqueInput
      | Prisma.UserFavoriteRestaurantWhereUniqueInput[];
    disconnect?:
      | Prisma.UserFavoriteRestaurantWhereUniqueInput
      | Prisma.UserFavoriteRestaurantWhereUniqueInput[];
    delete?:
      | Prisma.UserFavoriteRestaurantWhereUniqueInput
      | Prisma.UserFavoriteRestaurantWhereUniqueInput[];
    connect?:
      | Prisma.UserFavoriteRestaurantWhereUniqueInput
      | Prisma.UserFavoriteRestaurantWhereUniqueInput[];
    update?:
      | Prisma.UserFavoriteRestaurantUpdateWithWhereUniqueWithoutRestaurantInput
      | Prisma.UserFavoriteRestaurantUpdateWithWhereUniqueWithoutRestaurantInput[];
    updateMany?:
      | Prisma.UserFavoriteRestaurantUpdateManyWithWhereWithoutRestaurantInput
      | Prisma.UserFavoriteRestaurantUpdateManyWithWhereWithoutRestaurantInput[];
    deleteMany?:
      | Prisma.UserFavoriteRestaurantScalarWhereInput
      | Prisma.UserFavoriteRestaurantScalarWhereInput[];
  };

export type UserFavoriteRestaurantCreateWithoutUserInput = {
  createdAt?: Date | string;
  restaurant: Prisma.RestaurantCreateNestedOneWithoutUsersWhoFavoritedInput;
};

export type UserFavoriteRestaurantUncheckedCreateWithoutUserInput = {
  restaurantId: string;
  createdAt?: Date | string;
};

export type UserFavoriteRestaurantCreateOrConnectWithoutUserInput = {
  where: Prisma.UserFavoriteRestaurantWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.UserFavoriteRestaurantCreateWithoutUserInput,
    Prisma.UserFavoriteRestaurantUncheckedCreateWithoutUserInput
  >;
};

export type UserFavoriteRestaurantCreateManyUserInputEnvelope = {
  data:
    | Prisma.UserFavoriteRestaurantCreateManyUserInput
    | Prisma.UserFavoriteRestaurantCreateManyUserInput[];
  skipDuplicates?: boolean;
};

export type UserFavoriteRestaurantUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserFavoriteRestaurantWhereUniqueInput;
  update: Prisma.XOR<
    Prisma.UserFavoriteRestaurantUpdateWithoutUserInput,
    Prisma.UserFavoriteRestaurantUncheckedUpdateWithoutUserInput
  >;
  create: Prisma.XOR<
    Prisma.UserFavoriteRestaurantCreateWithoutUserInput,
    Prisma.UserFavoriteRestaurantUncheckedCreateWithoutUserInput
  >;
};

export type UserFavoriteRestaurantUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserFavoriteRestaurantWhereUniqueInput;
  data: Prisma.XOR<
    Prisma.UserFavoriteRestaurantUpdateWithoutUserInput,
    Prisma.UserFavoriteRestaurantUncheckedUpdateWithoutUserInput
  >;
};

export type UserFavoriteRestaurantUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserFavoriteRestaurantScalarWhereInput;
  data: Prisma.XOR<
    Prisma.UserFavoriteRestaurantUpdateManyMutationInput,
    Prisma.UserFavoriteRestaurantUncheckedUpdateManyWithoutUserInput
  >;
};

export type UserFavoriteRestaurantScalarWhereInput = {
  AND?:
    | Prisma.UserFavoriteRestaurantScalarWhereInput
    | Prisma.UserFavoriteRestaurantScalarWhereInput[];
  OR?: Prisma.UserFavoriteRestaurantScalarWhereInput[];
  NOT?:
    | Prisma.UserFavoriteRestaurantScalarWhereInput
    | Prisma.UserFavoriteRestaurantScalarWhereInput[];
  userId?: Prisma.StringFilter<"UserFavoriteRestaurant"> | string;
  restaurantId?: Prisma.StringFilter<"UserFavoriteRestaurant"> | string;
  createdAt?: Prisma.DateTimeFilter<"UserFavoriteRestaurant"> | Date | string;
};

export type UserFavoriteRestaurantCreateWithoutRestaurantInput = {
  createdAt?: Date | string;
  user: Prisma.UserCreateNestedOneWithoutFavoriteRestaurantsInput;
};

export type UserFavoriteRestaurantUncheckedCreateWithoutRestaurantInput = {
  userId: string;
  createdAt?: Date | string;
};

export type UserFavoriteRestaurantCreateOrConnectWithoutRestaurantInput = {
  where: Prisma.UserFavoriteRestaurantWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.UserFavoriteRestaurantCreateWithoutRestaurantInput,
    Prisma.UserFavoriteRestaurantUncheckedCreateWithoutRestaurantInput
  >;
};

export type UserFavoriteRestaurantCreateManyRestaurantInputEnvelope = {
  data:
    | Prisma.UserFavoriteRestaurantCreateManyRestaurantInput
    | Prisma.UserFavoriteRestaurantCreateManyRestaurantInput[];
  skipDuplicates?: boolean;
};

export type UserFavoriteRestaurantUpsertWithWhereUniqueWithoutRestaurantInput =
  {
    where: Prisma.UserFavoriteRestaurantWhereUniqueInput;
    update: Prisma.XOR<
      Prisma.UserFavoriteRestaurantUpdateWithoutRestaurantInput,
      Prisma.UserFavoriteRestaurantUncheckedUpdateWithoutRestaurantInput
    >;
    create: Prisma.XOR<
      Prisma.UserFavoriteRestaurantCreateWithoutRestaurantInput,
      Prisma.UserFavoriteRestaurantUncheckedCreateWithoutRestaurantInput
    >;
  };

export type UserFavoriteRestaurantUpdateWithWhereUniqueWithoutRestaurantInput =
  {
    where: Prisma.UserFavoriteRestaurantWhereUniqueInput;
    data: Prisma.XOR<
      Prisma.UserFavoriteRestaurantUpdateWithoutRestaurantInput,
      Prisma.UserFavoriteRestaurantUncheckedUpdateWithoutRestaurantInput
    >;
  };

export type UserFavoriteRestaurantUpdateManyWithWhereWithoutRestaurantInput = {
  where: Prisma.UserFavoriteRestaurantScalarWhereInput;
  data: Prisma.XOR<
    Prisma.UserFavoriteRestaurantUpdateManyMutationInput,
    Prisma.UserFavoriteRestaurantUncheckedUpdateManyWithoutRestaurantInput
  >;
};

export type UserFavoriteRestaurantCreateManyUserInput = {
  restaurantId: string;
  createdAt?: Date | string;
};

export type UserFavoriteRestaurantUpdateWithoutUserInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  restaurant?: Prisma.RestaurantUpdateOneRequiredWithoutUsersWhoFavoritedNestedInput;
};

export type UserFavoriteRestaurantUncheckedUpdateWithoutUserInput = {
  restaurantId?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type UserFavoriteRestaurantUncheckedUpdateManyWithoutUserInput = {
  restaurantId?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type UserFavoriteRestaurantCreateManyRestaurantInput = {
  userId: string;
  createdAt?: Date | string;
};

export type UserFavoriteRestaurantUpdateWithoutRestaurantInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  user?: Prisma.UserUpdateOneRequiredWithoutFavoriteRestaurantsNestedInput;
};

export type UserFavoriteRestaurantUncheckedUpdateWithoutRestaurantInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type UserFavoriteRestaurantUncheckedUpdateManyWithoutRestaurantInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type UserFavoriteRestaurantSelect<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    userId?: boolean;
    restaurantId?: boolean;
    createdAt?: boolean;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
    restaurant?: boolean | Prisma.RestaurantDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["userFavoriteRestaurant"]
>;

export type UserFavoriteRestaurantSelectCreateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    userId?: boolean;
    restaurantId?: boolean;
    createdAt?: boolean;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
    restaurant?: boolean | Prisma.RestaurantDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["userFavoriteRestaurant"]
>;

export type UserFavoriteRestaurantSelectUpdateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    userId?: boolean;
    restaurantId?: boolean;
    createdAt?: boolean;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
    restaurant?: boolean | Prisma.RestaurantDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["userFavoriteRestaurant"]
>;

export type UserFavoriteRestaurantSelectScalar = {
  userId?: boolean;
  restaurantId?: boolean;
  createdAt?: boolean;
};

export type UserFavoriteRestaurantOmit<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  "userId" | "restaurantId" | "createdAt",
  ExtArgs["result"]["userFavoriteRestaurant"]
>;
export type UserFavoriteRestaurantInclude<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  restaurant?: boolean | Prisma.RestaurantDefaultArgs<ExtArgs>;
};
export type UserFavoriteRestaurantIncludeCreateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  restaurant?: boolean | Prisma.RestaurantDefaultArgs<ExtArgs>;
};
export type UserFavoriteRestaurantIncludeUpdateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  restaurant?: boolean | Prisma.RestaurantDefaultArgs<ExtArgs>;
};

export type $UserFavoriteRestaurantPayload<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: "UserFavoriteRestaurant";
  objects: {
    user: Prisma.$UserPayload<ExtArgs>;
    restaurant: Prisma.$RestaurantPayload<ExtArgs>;
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      userId: string;
      restaurantId: string;
      createdAt: Date;
    },
    ExtArgs["result"]["userFavoriteRestaurant"]
  >;
  composites: {};
};

export type UserFavoriteRestaurantGetPayload<
  S extends boolean | null | undefined | UserFavoriteRestaurantDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$UserFavoriteRestaurantPayload, S>;

export type UserFavoriteRestaurantCountArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<
  UserFavoriteRestaurantFindManyArgs,
  "select" | "include" | "distinct" | "omit"
> & {
  select?: UserFavoriteRestaurantCountAggregateInputType | true;
};

export interface UserFavoriteRestaurantDelegate<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>["model"]["UserFavoriteRestaurant"];
    meta: { name: "UserFavoriteRestaurant" };
  };
  /**
   * Find zero or one UserFavoriteRestaurant that matches the filter.
   * @param {UserFavoriteRestaurantFindUniqueArgs} args - Arguments to find a UserFavoriteRestaurant
   * @example
   * // Get one UserFavoriteRestaurant
   * const userFavoriteRestaurant = await prisma.userFavoriteRestaurant.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserFavoriteRestaurantFindUniqueArgs>(
    args: Prisma.SelectSubset<T, UserFavoriteRestaurantFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__UserFavoriteRestaurantClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserFavoriteRestaurantPayload<ExtArgs>,
      T,
      "findUnique",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one UserFavoriteRestaurant that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserFavoriteRestaurantFindUniqueOrThrowArgs} args - Arguments to find a UserFavoriteRestaurant
   * @example
   * // Get one UserFavoriteRestaurant
   * const userFavoriteRestaurant = await prisma.userFavoriteRestaurant.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserFavoriteRestaurantFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<
      T,
      UserFavoriteRestaurantFindUniqueOrThrowArgs<ExtArgs>
    >,
  ): Prisma.Prisma__UserFavoriteRestaurantClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserFavoriteRestaurantPayload<ExtArgs>,
      T,
      "findUniqueOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first UserFavoriteRestaurant that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFavoriteRestaurantFindFirstArgs} args - Arguments to find a UserFavoriteRestaurant
   * @example
   * // Get one UserFavoriteRestaurant
   * const userFavoriteRestaurant = await prisma.userFavoriteRestaurant.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserFavoriteRestaurantFindFirstArgs>(
    args?: Prisma.SelectSubset<T, UserFavoriteRestaurantFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__UserFavoriteRestaurantClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserFavoriteRestaurantPayload<ExtArgs>,
      T,
      "findFirst",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first UserFavoriteRestaurant that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFavoriteRestaurantFindFirstOrThrowArgs} args - Arguments to find a UserFavoriteRestaurant
   * @example
   * // Get one UserFavoriteRestaurant
   * const userFavoriteRestaurant = await prisma.userFavoriteRestaurant.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserFavoriteRestaurantFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<
      T,
      UserFavoriteRestaurantFindFirstOrThrowArgs<ExtArgs>
    >,
  ): Prisma.Prisma__UserFavoriteRestaurantClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserFavoriteRestaurantPayload<ExtArgs>,
      T,
      "findFirstOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more UserFavoriteRestaurants that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFavoriteRestaurantFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserFavoriteRestaurants
   * const userFavoriteRestaurants = await prisma.userFavoriteRestaurant.findMany()
   *
   * // Get first 10 UserFavoriteRestaurants
   * const userFavoriteRestaurants = await prisma.userFavoriteRestaurant.findMany({ take: 10 })
   *
   * // Only select the `userId`
   * const userFavoriteRestaurantWithUserIdOnly = await prisma.userFavoriteRestaurant.findMany({ select: { userId: true } })
   *
   */
  findMany<T extends UserFavoriteRestaurantFindManyArgs>(
    args?: Prisma.SelectSubset<T, UserFavoriteRestaurantFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$UserFavoriteRestaurantPayload<ExtArgs>,
      T,
      "findMany",
      GlobalOmitOptions
    >
  >;

  /**
   * Create a UserFavoriteRestaurant.
   * @param {UserFavoriteRestaurantCreateArgs} args - Arguments to create a UserFavoriteRestaurant.
   * @example
   * // Create one UserFavoriteRestaurant
   * const UserFavoriteRestaurant = await prisma.userFavoriteRestaurant.create({
   *   data: {
   *     // ... data to create a UserFavoriteRestaurant
   *   }
   * })
   *
   */
  create<T extends UserFavoriteRestaurantCreateArgs>(
    args: Prisma.SelectSubset<T, UserFavoriteRestaurantCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__UserFavoriteRestaurantClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserFavoriteRestaurantPayload<ExtArgs>,
      T,
      "create",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many UserFavoriteRestaurants.
   * @param {UserFavoriteRestaurantCreateManyArgs} args - Arguments to create many UserFavoriteRestaurants.
   * @example
   * // Create many UserFavoriteRestaurants
   * const userFavoriteRestaurant = await prisma.userFavoriteRestaurant.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends UserFavoriteRestaurantCreateManyArgs>(
    args?: Prisma.SelectSubset<
      T,
      UserFavoriteRestaurantCreateManyArgs<ExtArgs>
    >,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many UserFavoriteRestaurants and returns the data saved in the database.
   * @param {UserFavoriteRestaurantCreateManyAndReturnArgs} args - Arguments to create many UserFavoriteRestaurants.
   * @example
   * // Create many UserFavoriteRestaurants
   * const userFavoriteRestaurant = await prisma.userFavoriteRestaurant.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many UserFavoriteRestaurants and only return the `userId`
   * const userFavoriteRestaurantWithUserIdOnly = await prisma.userFavoriteRestaurant.createManyAndReturn({
   *   select: { userId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends UserFavoriteRestaurantCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<
      T,
      UserFavoriteRestaurantCreateManyAndReturnArgs<ExtArgs>
    >,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$UserFavoriteRestaurantPayload<ExtArgs>,
      T,
      "createManyAndReturn",
      GlobalOmitOptions
    >
  >;

  /**
   * Delete a UserFavoriteRestaurant.
   * @param {UserFavoriteRestaurantDeleteArgs} args - Arguments to delete one UserFavoriteRestaurant.
   * @example
   * // Delete one UserFavoriteRestaurant
   * const UserFavoriteRestaurant = await prisma.userFavoriteRestaurant.delete({
   *   where: {
   *     // ... filter to delete one UserFavoriteRestaurant
   *   }
   * })
   *
   */
  delete<T extends UserFavoriteRestaurantDeleteArgs>(
    args: Prisma.SelectSubset<T, UserFavoriteRestaurantDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__UserFavoriteRestaurantClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserFavoriteRestaurantPayload<ExtArgs>,
      T,
      "delete",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one UserFavoriteRestaurant.
   * @param {UserFavoriteRestaurantUpdateArgs} args - Arguments to update one UserFavoriteRestaurant.
   * @example
   * // Update one UserFavoriteRestaurant
   * const userFavoriteRestaurant = await prisma.userFavoriteRestaurant.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends UserFavoriteRestaurantUpdateArgs>(
    args: Prisma.SelectSubset<T, UserFavoriteRestaurantUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__UserFavoriteRestaurantClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserFavoriteRestaurantPayload<ExtArgs>,
      T,
      "update",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more UserFavoriteRestaurants.
   * @param {UserFavoriteRestaurantDeleteManyArgs} args - Arguments to filter UserFavoriteRestaurants to delete.
   * @example
   * // Delete a few UserFavoriteRestaurants
   * const { count } = await prisma.userFavoriteRestaurant.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends UserFavoriteRestaurantDeleteManyArgs>(
    args?: Prisma.SelectSubset<
      T,
      UserFavoriteRestaurantDeleteManyArgs<ExtArgs>
    >,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more UserFavoriteRestaurants.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFavoriteRestaurantUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserFavoriteRestaurants
   * const userFavoriteRestaurant = await prisma.userFavoriteRestaurant.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends UserFavoriteRestaurantUpdateManyArgs>(
    args: Prisma.SelectSubset<T, UserFavoriteRestaurantUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more UserFavoriteRestaurants and returns the data updated in the database.
   * @param {UserFavoriteRestaurantUpdateManyAndReturnArgs} args - Arguments to update many UserFavoriteRestaurants.
   * @example
   * // Update many UserFavoriteRestaurants
   * const userFavoriteRestaurant = await prisma.userFavoriteRestaurant.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more UserFavoriteRestaurants and only return the `userId`
   * const userFavoriteRestaurantWithUserIdOnly = await prisma.userFavoriteRestaurant.updateManyAndReturn({
   *   select: { userId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends UserFavoriteRestaurantUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<
      T,
      UserFavoriteRestaurantUpdateManyAndReturnArgs<ExtArgs>
    >,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$UserFavoriteRestaurantPayload<ExtArgs>,
      T,
      "updateManyAndReturn",
      GlobalOmitOptions
    >
  >;

  /**
   * Create or update one UserFavoriteRestaurant.
   * @param {UserFavoriteRestaurantUpsertArgs} args - Arguments to update or create a UserFavoriteRestaurant.
   * @example
   * // Update or create a UserFavoriteRestaurant
   * const userFavoriteRestaurant = await prisma.userFavoriteRestaurant.upsert({
   *   create: {
   *     // ... data to create a UserFavoriteRestaurant
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserFavoriteRestaurant we want to update
   *   }
   * })
   */
  upsert<T extends UserFavoriteRestaurantUpsertArgs>(
    args: Prisma.SelectSubset<T, UserFavoriteRestaurantUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__UserFavoriteRestaurantClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserFavoriteRestaurantPayload<ExtArgs>,
      T,
      "upsert",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of UserFavoriteRestaurants.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFavoriteRestaurantCountArgs} args - Arguments to filter UserFavoriteRestaurants to count.
   * @example
   * // Count the number of UserFavoriteRestaurants
   * const count = await prisma.userFavoriteRestaurant.count({
   *   where: {
   *     // ... the filter for the UserFavoriteRestaurants we want to count
   *   }
   * })
   **/
  count<T extends UserFavoriteRestaurantCountArgs>(
    args?: Prisma.Subset<T, UserFavoriteRestaurantCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<"select", any>
      ? T["select"] extends true
        ? number
        : Prisma.GetScalarType<
            T["select"],
            UserFavoriteRestaurantCountAggregateOutputType
          >
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a UserFavoriteRestaurant.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFavoriteRestaurantAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends UserFavoriteRestaurantAggregateArgs>(
    args: Prisma.Subset<T, UserFavoriteRestaurantAggregateArgs>,
  ): Prisma.PrismaPromise<GetUserFavoriteRestaurantAggregateType<T>>;

  /**
   * Group by UserFavoriteRestaurant.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFavoriteRestaurantGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends UserFavoriteRestaurantGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<"skip", Prisma.Keys<T>>,
      Prisma.Extends<"take", Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserFavoriteRestaurantGroupByArgs["orderBy"] }
      : { orderBy?: UserFavoriteRestaurantGroupByArgs["orderBy"] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T["having"]>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    "Field ",
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ];
          }[HavingFields]
        : "take" extends Prisma.Keys<T>
          ? "orderBy" extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : "skip" extends Prisma.Keys<T>
            ? "orderBy" extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<
      T,
      UserFavoriteRestaurantGroupByArgs,
      OrderByArg
    > &
      InputErrors,
  ): {} extends InputErrors
    ? GetUserFavoriteRestaurantGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the UserFavoriteRestaurant model
   */
  readonly fields: UserFavoriteRestaurantFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserFavoriteRestaurant.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserFavoriteRestaurantClient<
  T,
  Null = never,
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise";
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>,
  ): Prisma.Prisma__UserClient<
    | runtime.Types.Result.GetResult<
        Prisma.$UserPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  restaurant<T extends Prisma.RestaurantDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.RestaurantDefaultArgs<ExtArgs>>,
  ): Prisma.Prisma__RestaurantClient<
    | runtime.Types.Result.GetResult<
        Prisma.$RestaurantPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the UserFavoriteRestaurant model
 */
export interface UserFavoriteRestaurantFieldRefs {
  readonly userId: Prisma.FieldRef<"UserFavoriteRestaurant", "String">;
  readonly restaurantId: Prisma.FieldRef<"UserFavoriteRestaurant", "String">;
  readonly createdAt: Prisma.FieldRef<"UserFavoriteRestaurant", "DateTime">;
}

// Custom InputTypes
/**
 * UserFavoriteRestaurant findUnique
 */
export type UserFavoriteRestaurantFindUniqueArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserFavoriteRestaurant
   */
  select?: Prisma.UserFavoriteRestaurantSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UserFavoriteRestaurant
   */
  omit?: Prisma.UserFavoriteRestaurantOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFavoriteRestaurantInclude<ExtArgs> | null;
  /**
   * Filter, which UserFavoriteRestaurant to fetch.
   */
  where: Prisma.UserFavoriteRestaurantWhereUniqueInput;
};

/**
 * UserFavoriteRestaurant findUniqueOrThrow
 */
export type UserFavoriteRestaurantFindUniqueOrThrowArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserFavoriteRestaurant
   */
  select?: Prisma.UserFavoriteRestaurantSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UserFavoriteRestaurant
   */
  omit?: Prisma.UserFavoriteRestaurantOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFavoriteRestaurantInclude<ExtArgs> | null;
  /**
   * Filter, which UserFavoriteRestaurant to fetch.
   */
  where: Prisma.UserFavoriteRestaurantWhereUniqueInput;
};

/**
 * UserFavoriteRestaurant findFirst
 */
export type UserFavoriteRestaurantFindFirstArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserFavoriteRestaurant
   */
  select?: Prisma.UserFavoriteRestaurantSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UserFavoriteRestaurant
   */
  omit?: Prisma.UserFavoriteRestaurantOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFavoriteRestaurantInclude<ExtArgs> | null;
  /**
   * Filter, which UserFavoriteRestaurant to fetch.
   */
  where?: Prisma.UserFavoriteRestaurantWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of UserFavoriteRestaurants to fetch.
   */
  orderBy?:
    | Prisma.UserFavoriteRestaurantOrderByWithRelationInput
    | Prisma.UserFavoriteRestaurantOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for UserFavoriteRestaurants.
   */
  cursor?: Prisma.UserFavoriteRestaurantWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` UserFavoriteRestaurants from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` UserFavoriteRestaurants.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of UserFavoriteRestaurants.
   */
  distinct?:
    | Prisma.UserFavoriteRestaurantScalarFieldEnum
    | Prisma.UserFavoriteRestaurantScalarFieldEnum[];
};

/**
 * UserFavoriteRestaurant findFirstOrThrow
 */
export type UserFavoriteRestaurantFindFirstOrThrowArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserFavoriteRestaurant
   */
  select?: Prisma.UserFavoriteRestaurantSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UserFavoriteRestaurant
   */
  omit?: Prisma.UserFavoriteRestaurantOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFavoriteRestaurantInclude<ExtArgs> | null;
  /**
   * Filter, which UserFavoriteRestaurant to fetch.
   */
  where?: Prisma.UserFavoriteRestaurantWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of UserFavoriteRestaurants to fetch.
   */
  orderBy?:
    | Prisma.UserFavoriteRestaurantOrderByWithRelationInput
    | Prisma.UserFavoriteRestaurantOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for UserFavoriteRestaurants.
   */
  cursor?: Prisma.UserFavoriteRestaurantWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` UserFavoriteRestaurants from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` UserFavoriteRestaurants.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of UserFavoriteRestaurants.
   */
  distinct?:
    | Prisma.UserFavoriteRestaurantScalarFieldEnum
    | Prisma.UserFavoriteRestaurantScalarFieldEnum[];
};

/**
 * UserFavoriteRestaurant findMany
 */
export type UserFavoriteRestaurantFindManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserFavoriteRestaurant
   */
  select?: Prisma.UserFavoriteRestaurantSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UserFavoriteRestaurant
   */
  omit?: Prisma.UserFavoriteRestaurantOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFavoriteRestaurantInclude<ExtArgs> | null;
  /**
   * Filter, which UserFavoriteRestaurants to fetch.
   */
  where?: Prisma.UserFavoriteRestaurantWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of UserFavoriteRestaurants to fetch.
   */
  orderBy?:
    | Prisma.UserFavoriteRestaurantOrderByWithRelationInput
    | Prisma.UserFavoriteRestaurantOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing UserFavoriteRestaurants.
   */
  cursor?: Prisma.UserFavoriteRestaurantWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` UserFavoriteRestaurants from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` UserFavoriteRestaurants.
   */
  skip?: number;
  distinct?:
    | Prisma.UserFavoriteRestaurantScalarFieldEnum
    | Prisma.UserFavoriteRestaurantScalarFieldEnum[];
};

/**
 * UserFavoriteRestaurant create
 */
export type UserFavoriteRestaurantCreateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserFavoriteRestaurant
   */
  select?: Prisma.UserFavoriteRestaurantSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UserFavoriteRestaurant
   */
  omit?: Prisma.UserFavoriteRestaurantOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFavoriteRestaurantInclude<ExtArgs> | null;
  /**
   * The data needed to create a UserFavoriteRestaurant.
   */
  data: Prisma.XOR<
    Prisma.UserFavoriteRestaurantCreateInput,
    Prisma.UserFavoriteRestaurantUncheckedCreateInput
  >;
};

/**
 * UserFavoriteRestaurant createMany
 */
export type UserFavoriteRestaurantCreateManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many UserFavoriteRestaurants.
   */
  data:
    | Prisma.UserFavoriteRestaurantCreateManyInput
    | Prisma.UserFavoriteRestaurantCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * UserFavoriteRestaurant createManyAndReturn
 */
export type UserFavoriteRestaurantCreateManyAndReturnArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserFavoriteRestaurant
   */
  select?: Prisma.UserFavoriteRestaurantSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the UserFavoriteRestaurant
   */
  omit?: Prisma.UserFavoriteRestaurantOmit<ExtArgs> | null;
  /**
   * The data used to create many UserFavoriteRestaurants.
   */
  data:
    | Prisma.UserFavoriteRestaurantCreateManyInput
    | Prisma.UserFavoriteRestaurantCreateManyInput[];
  skipDuplicates?: boolean;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFavoriteRestaurantIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * UserFavoriteRestaurant update
 */
export type UserFavoriteRestaurantUpdateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserFavoriteRestaurant
   */
  select?: Prisma.UserFavoriteRestaurantSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UserFavoriteRestaurant
   */
  omit?: Prisma.UserFavoriteRestaurantOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFavoriteRestaurantInclude<ExtArgs> | null;
  /**
   * The data needed to update a UserFavoriteRestaurant.
   */
  data: Prisma.XOR<
    Prisma.UserFavoriteRestaurantUpdateInput,
    Prisma.UserFavoriteRestaurantUncheckedUpdateInput
  >;
  /**
   * Choose, which UserFavoriteRestaurant to update.
   */
  where: Prisma.UserFavoriteRestaurantWhereUniqueInput;
};

/**
 * UserFavoriteRestaurant updateMany
 */
export type UserFavoriteRestaurantUpdateManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update UserFavoriteRestaurants.
   */
  data: Prisma.XOR<
    Prisma.UserFavoriteRestaurantUpdateManyMutationInput,
    Prisma.UserFavoriteRestaurantUncheckedUpdateManyInput
  >;
  /**
   * Filter which UserFavoriteRestaurants to update
   */
  where?: Prisma.UserFavoriteRestaurantWhereInput;
  /**
   * Limit how many UserFavoriteRestaurants to update.
   */
  limit?: number;
};

/**
 * UserFavoriteRestaurant updateManyAndReturn
 */
export type UserFavoriteRestaurantUpdateManyAndReturnArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserFavoriteRestaurant
   */
  select?: Prisma.UserFavoriteRestaurantSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the UserFavoriteRestaurant
   */
  omit?: Prisma.UserFavoriteRestaurantOmit<ExtArgs> | null;
  /**
   * The data used to update UserFavoriteRestaurants.
   */
  data: Prisma.XOR<
    Prisma.UserFavoriteRestaurantUpdateManyMutationInput,
    Prisma.UserFavoriteRestaurantUncheckedUpdateManyInput
  >;
  /**
   * Filter which UserFavoriteRestaurants to update
   */
  where?: Prisma.UserFavoriteRestaurantWhereInput;
  /**
   * Limit how many UserFavoriteRestaurants to update.
   */
  limit?: number;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFavoriteRestaurantIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * UserFavoriteRestaurant upsert
 */
export type UserFavoriteRestaurantUpsertArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserFavoriteRestaurant
   */
  select?: Prisma.UserFavoriteRestaurantSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UserFavoriteRestaurant
   */
  omit?: Prisma.UserFavoriteRestaurantOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFavoriteRestaurantInclude<ExtArgs> | null;
  /**
   * The filter to search for the UserFavoriteRestaurant to update in case it exists.
   */
  where: Prisma.UserFavoriteRestaurantWhereUniqueInput;
  /**
   * In case the UserFavoriteRestaurant found by the `where` argument doesn't exist, create a new UserFavoriteRestaurant with this data.
   */
  create: Prisma.XOR<
    Prisma.UserFavoriteRestaurantCreateInput,
    Prisma.UserFavoriteRestaurantUncheckedCreateInput
  >;
  /**
   * In case the UserFavoriteRestaurant was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.UserFavoriteRestaurantUpdateInput,
    Prisma.UserFavoriteRestaurantUncheckedUpdateInput
  >;
};

/**
 * UserFavoriteRestaurant delete
 */
export type UserFavoriteRestaurantDeleteArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserFavoriteRestaurant
   */
  select?: Prisma.UserFavoriteRestaurantSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UserFavoriteRestaurant
   */
  omit?: Prisma.UserFavoriteRestaurantOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFavoriteRestaurantInclude<ExtArgs> | null;
  /**
   * Filter which UserFavoriteRestaurant to delete.
   */
  where: Prisma.UserFavoriteRestaurantWhereUniqueInput;
};

/**
 * UserFavoriteRestaurant deleteMany
 */
export type UserFavoriteRestaurantDeleteManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which UserFavoriteRestaurants to delete
   */
  where?: Prisma.UserFavoriteRestaurantWhereInput;
  /**
   * Limit how many UserFavoriteRestaurants to delete.
   */
  limit?: number;
};

/**
 * UserFavoriteRestaurant without action
 */
export type UserFavoriteRestaurantDefaultArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserFavoriteRestaurant
   */
  select?: Prisma.UserFavoriteRestaurantSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UserFavoriteRestaurant
   */
  omit?: Prisma.UserFavoriteRestaurantOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFavoriteRestaurantInclude<ExtArgs> | null;
};
